// <auto-generated />
using System;
using JD.com.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JD.com.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240510094002_ne")]
    partial class ne
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CollegeCourses", b =>
                {
                    b.Property<int>("CollegeId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("CollegeId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("CollegeCourses");
                });

            modelBuilder.Entity("JD.com.Models.College", b =>
                {
                    b.Property<int>("CollegeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CollegeId"));

                    b.Property<string>("CollegeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("CollegeId");

                    b.HasIndex("StateId");

                    b.ToTable("College");

                    b.HasData(
                        new
                        {
                            CollegeId = 1,
                            CollegeName = "BFIT",
                            CourseId = 0,
                            StateId = 4
                        },
                        new
                        {
                            CollegeId = 2,
                            CollegeName = "Baba Farid College",
                            CourseId = 0,
                            StateId = 5
                        },
                        new
                        {
                            CollegeId = 3,
                            CollegeName = "Degree College Baramulla",
                            CourseId = 0,
                            StateId = 1
                        },
                        new
                        {
                            CollegeId = 5,
                            CollegeName = "Dev Bhoomi",
                            CourseId = 0,
                            StateId = 4
                        },
                        new
                        {
                            CollegeId = 6,
                            CollegeName = "Dhoon International",
                            CourseId = 0,
                            StateId = 4
                        },
                        new
                        {
                            CollegeId = 7,
                            CollegeName = "Dolphin College",
                            CourseId = 0,
                            StateId = 4
                        },
                        new
                        {
                            CollegeId = 8,
                            CollegeName = "Guru Nanak College",
                            CourseId = 0,
                            StateId = 4
                        },
                        new
                        {
                            CollegeId = 9,
                            CollegeName = "LPU",
                            CourseId = 0,
                            StateId = 5
                        },
                        new
                        {
                            CollegeId = 10,
                            CollegeName = "Chandigarh College of Hotel Management ",
                            CourseId = 0,
                            StateId = 5
                        },
                        new
                        {
                            CollegeId = 11,
                            CollegeName = "Chandigarh Group of Colleges ",
                            CourseId = 0,
                            StateId = 5
                        },
                        new
                        {
                            CollegeId = 12,
                            CollegeName = "Chandigarh Group of Colleges ",
                            CourseId = 0,
                            StateId = 5
                        },
                        new
                        {
                            CollegeId = 13,
                            CollegeName = "Degree College Pattan",
                            CourseId = 0,
                            StateId = 1
                        },
                        new
                        {
                            CollegeId = 14,
                            CollegeName = "Degree College Singpora",
                            CourseId = 0,
                            StateId = 1
                        },
                        new
                        {
                            CollegeId = 15,
                            CollegeName = "Amar Singh College",
                            CourseId = 0,
                            StateId = 1
                        },
                        new
                        {
                            CollegeId = 16,
                            CollegeName = "NIT",
                            CourseId = 0,
                            StateId = 1
                        },
                        new
                        {
                            CollegeId = 17,
                            CollegeName = "IUST",
                            CourseId = 0,
                            StateId = 1
                        },
                        new
                        {
                            CollegeId = 18,
                            CollegeName = "Degree College Bemina",
                            CourseId = 0,
                            StateId = 1
                        },
                        new
                        {
                            CollegeId = 19,
                            CollegeName = "Banglore College Of technology",
                            CourseId = 0,
                            StateId = 6
                        },
                        new
                        {
                            CollegeId = 20,
                            CollegeName = "Christ University",
                            CourseId = 0,
                            StateId = 6
                        },
                        new
                        {
                            CollegeId = 21,
                            CollegeName = "Bangalore University",
                            CourseId = 0,
                            StateId = 6
                        },
                        new
                        {
                            CollegeId = 22,
                            CollegeName = "Mount Carmel College Autonomous",
                            CourseId = 0,
                            StateId = 6
                        },
                        new
                        {
                            CollegeId = 23,
                            CollegeName = "Indian Institute Of Management–Bangalore",
                            CourseId = 0,
                            StateId = 6
                        },
                        new
                        {
                            CollegeId = 24,
                            CollegeName = "R. V. College of Engineering",
                            CourseId = 0,
                            StateId = 6
                        },
                        new
                        {
                            CollegeId = 25,
                            CollegeName = "Delhi University",
                            CourseId = 0,
                            StateId = 2
                        },
                        new
                        {
                            CollegeId = 26,
                            CollegeName = "Jamia Millia Islamia",
                            CourseId = 0,
                            StateId = 2
                        },
                        new
                        {
                            CollegeId = 27,
                            CollegeName = "Indian Institute Of Technology Delhi",
                            CourseId = 0,
                            StateId = 2
                        },
                        new
                        {
                            CollegeId = 28,
                            CollegeName = "All India Institute Of Medical Sciences Delhi",
                            CourseId = 0,
                            StateId = 2
                        },
                        new
                        {
                            CollegeId = 29,
                            CollegeName = "Delhi Technological University",
                            CourseId = 0,
                            StateId = 2
                        },
                        new
                        {
                            CollegeId = 30,
                            CollegeName = "Jamia Hamdard University",
                            CourseId = 0,
                            StateId = 2
                        });
                });

            modelBuilder.Entity("JD.com.Models.CourseGroup", b =>
                {
                    b.Property<int>("CourseGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseGroupId"));

                    b.Property<string>("CourseGroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseGroupId");

                    b.ToTable("CourseGroup");

                    b.HasData(
                        new
                        {
                            CourseGroupId = 1,
                            CourseGroupName = "Information Technology"
                        },
                        new
                        {
                            CourseGroupId = 2,
                            CourseGroupName = "Engineering"
                        },
                        new
                        {
                            CourseGroupId = 3,
                            CourseGroupName = "Science"
                        },
                        new
                        {
                            CourseGroupId = 4,
                            CourseGroupName = "Hotel Management"
                        });
                });

            modelBuilder.Entity("JD.com.Models.Courses", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<int>("CollegeId")
                        .HasColumnType("int");

                    b.Property<int>("CourseGroupId")
                        .HasColumnType("int");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseId");

                    b.HasIndex("CourseGroupId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            CollegeId = 0,
                            CourseGroupId = 1,
                            CourseName = "BCA"
                        },
                        new
                        {
                            CourseId = 2,
                            CollegeId = 0,
                            CourseGroupId = 1,
                            CourseName = "BscIT"
                        },
                        new
                        {
                            CourseId = 3,
                            CollegeId = 0,
                            CourseGroupId = 1,
                            CourseName = "MCA"
                        },
                        new
                        {
                            CourseId = 4,
                            CollegeId = 0,
                            CourseGroupId = 1,
                            CourseName = "MSC IT"
                        },
                        new
                        {
                            CourseId = 5,
                            CollegeId = 0,
                            CourseGroupId = 1,
                            CourseName = "BTEC COMPUTER"
                        },
                        new
                        {
                            CourseId = 6,
                            CollegeId = 0,
                            CourseGroupId = 2,
                            CourseName = "BTECH CIVIL"
                        },
                        new
                        {
                            CourseId = 7,
                            CollegeId = 0,
                            CourseGroupId = 2,
                            CourseName = "BTECH MECHINICAL"
                        },
                        new
                        {
                            CourseId = 8,
                            CollegeId = 0,
                            CourseGroupId = 2,
                            CourseName = "BTECH ELECTRICAL"
                        },
                        new
                        {
                            CourseId = 9,
                            CollegeId = 0,
                            CourseGroupId = 2,
                            CourseName = "MTECH CIVIL"
                        },
                        new
                        {
                            CourseId = 10,
                            CollegeId = 0,
                            CourseGroupId = 2,
                            CourseName = "MTECH MECHINICAL"
                        },
                        new
                        {
                            CourseId = 11,
                            CollegeId = 0,
                            CourseGroupId = 2,
                            CourseName = "MTECH ELECTRICAL"
                        },
                        new
                        {
                            CourseId = 12,
                            CollegeId = 0,
                            CourseGroupId = 3,
                            CourseName = "BSC BIOLOGY"
                        },
                        new
                        {
                            CourseId = 13,
                            CollegeId = 0,
                            CourseGroupId = 3,
                            CourseName = "MSC BIOLOGY"
                        },
                        new
                        {
                            CourseId = 14,
                            CollegeId = 0,
                            CourseGroupId = 3,
                            CourseName = "BSC Chemistry"
                        },
                        new
                        {
                            CourseId = 15,
                            CollegeId = 0,
                            CourseGroupId = 3,
                            CourseName = "MSC Chemistry"
                        },
                        new
                        {
                            CourseId = 16,
                            CollegeId = 0,
                            CourseGroupId = 3,
                            CourseName = "MSC Physics"
                        },
                        new
                        {
                            CourseId = 17,
                            CollegeId = 0,
                            CourseGroupId = 3,
                            CourseName = "BSC Physics"
                        },
                        new
                        {
                            CourseId = 18,
                            CollegeId = 0,
                            CourseGroupId = 4,
                            CourseName = "Bachelor Of Hotel Management."
                        },
                        new
                        {
                            CourseId = 19,
                            CollegeId = 0,
                            CourseGroupId = 4,
                            CourseName = "Masters Of Hotel Management."
                        },
                        new
                        {
                            CourseId = 20,
                            CollegeId = 0,
                            CourseGroupId = 4,
                            CourseName = "Diploma Of Hotel Management."
                        },
                        new
                        {
                            CourseId = 21,
                            CollegeId = 0,
                            CourseGroupId = 4,
                            CourseName = "BSc in Hospitality And Hotel Administration."
                        },
                        new
                        {
                            CourseId = 22,
                            CollegeId = 0,
                            CourseGroupId = 4,
                            CourseName = "Diploma in Food and Beverage services."
                        },
                        new
                        {
                            CourseId = 23,
                            CollegeId = 0,
                            CourseGroupId = 4,
                            CourseName = "Advanced Diploma in Hospitality Management."
                        });
                });

            modelBuilder.Entity("JD.com.Models.Exams", b =>
                {
                    b.Property<int>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamId"));

                    b.Property<int>("CourseGroupId")
                        .HasColumnType("int");

                    b.Property<int?>("CoursesCourseId")
                        .HasColumnType("int");

                    b.Property<string>("ExamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExamId");

                    b.HasIndex("CourseGroupId");

                    b.HasIndex("CoursesCourseId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("JD.com.Models.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateId"));

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StateId");

                    b.ToTable("State");

                    b.HasData(
                        new
                        {
                            StateId = 1,
                            StateName = "J&K"
                        },
                        new
                        {
                            StateId = 2,
                            StateName = "Delhi"
                        },
                        new
                        {
                            StateId = 4,
                            StateName = "Uttarakhand"
                        },
                        new
                        {
                            StateId = 5,
                            StateName = "Punjab"
                        },
                        new
                        {
                            StateId = 6,
                            StateName = "Banglore"
                        });
                });

            modelBuilder.Entity("CollegeCourses", b =>
                {
                    b.HasOne("JD.com.Models.Courses", null)
                        .WithMany()
                        .HasForeignKey("CollegeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JD.com.Models.College", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JD.com.Models.College", b =>
                {
                    b.HasOne("JD.com.Models.State", "state")
                        .WithMany("Colleges")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("state");
                });

            modelBuilder.Entity("JD.com.Models.Courses", b =>
                {
                    b.HasOne("JD.com.Models.CourseGroup", "CourseGroup")
                        .WithMany("Courses")
                        .HasForeignKey("CourseGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseGroup");
                });

            modelBuilder.Entity("JD.com.Models.Exams", b =>
                {
                    b.HasOne("JD.com.Models.CourseGroup", "CourseGroup")
                        .WithMany()
                        .HasForeignKey("CourseGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JD.com.Models.Courses", null)
                        .WithMany("Exams")
                        .HasForeignKey("CoursesCourseId");

                    b.Navigation("CourseGroup");
                });

            modelBuilder.Entity("JD.com.Models.CourseGroup", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("JD.com.Models.Courses", b =>
                {
                    b.Navigation("Exams");
                });

            modelBuilder.Entity("JD.com.Models.State", b =>
                {
                    b.Navigation("Colleges");
                });
#pragma warning restore 612, 618
        }
    }
}
